### PR TITLE
String Pattern solved and ready to be reviewed. 

### PR DESCRIPTION
**Pull request by AhWalidShahab**
The string_pattern function checks whether a given pattern can be mapped to any part of a provided string. Each unique character in the pattern must correspond to a unique character in the string.

Functionality:
Iterates over substrings of the given string, each the same length as the pattern. Tries to map each character in the pattern to a character in the substring. Uses a dictionary for character mappings and a set to track already mapped characters. Ensures that each character in the pattern consistently maps to the same character in the string and that no two different characters in the pattern map to the same character in the string. Returns True if a valid mapping is found; otherwise, False.

Use Case:
This function is useful for scenarios that require identifying a specific sequence of unique characters in a string, important in string analysis and parsing tasks.

Overall, string_pattern is a specialized function for pattern-to-string matching, emphasizing the uniqueness and consistency of character mappings.

- [ ] PR's title includes the challenge's name and language
- [x] PR has short and clear description of the challenge
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] all conflicts are resolved (if any)
- [x] It is linked to an issue in the appropriate column of the project board
- [ ] feedback is addressed (if any, and if it is appropriate feedback.)

## README Documentation

- [x] The solution is documented in `/src/README.md`
- [x] The markdown source is formatted
- [x] Spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [ ] All links and images work
- [x] The README documents the solution's behavior, strategy(ies) and implementation(s)
- [x] There are use cases in code blocks to illustrate the function's behavior

## Python Files

- [x] There is a module header
- [x] There is a module docstring
- [x] File names are in snake_case
- [x] Test files are named `test_<module_name>.py`

## Function Docstring

- [x] Behavior description
- [x] Parameter description
- [x] Return value description
- [x] Include any assumptions
- [x] Include 3 or more (passing!) doctests
- [x] Include 1-2 use cases (if necessary)

## Function Implementation

- [x] The solution is not is not copied from [djeada](https://github.com/djeada/Algorithms-And-Data-Structures)
- [x] The code is auto-formatted
- [x] The code has no (reasonable) linting mistakes
- [x] Variables are named with snake_case
- [x] The function has a clear and helpful name
- [x] The file's name matches the function name
- [x] The code follows the strategy as simply as possible
- [x] Variable names are clear and helpful
- [x] Comments explain the strategy (if necessary)
- [x] There are type annotations
- [ ] (challenge) The code includes defensive assertions

## Unit Test Suite

- [x] The test class has a helpful name in PascalCase
- [x] The test class has a docstring
- Each unit test has
  - [x] A helpful name
  - [x] A clear docstring
  - [x] Only one assertion
- [x] All tests pass
- [x] There are tests for defensive assertions
- [x] There are tests for boundary cases
- [ ] Test suite includes black-box and glass-box tests

### CODE REVIEW

**Review by AnnaShliapkina — CHANGES_REQUESTED** [review]
1. Add README
2. Add docstrings to string_pattern.py and test file
3. Code are clear and all tests are passed, so read requirements an README to this pull REquest and based on unchecked rows make changes (almost all are docstrings)

**Review by DmytroLyt — CHANGES_REQUESTED** [review]
- PR it is assigned to the owner ( Do not have assigned person, Need to add) 

Python Files
- There is a module header ( Doesn`t have, Need to add)
- There is a module docstring ( Doesn`t have, Need to add)

Function Docstring 
- Parameter description ( Doesn`t have, Need to add)
- Return value description ( Doesn`t have, Need to add)

Unit Test Suite
- The test class has a docstring  ( Doesn`t have, Need to add)

**Comment by AhWalidShahab** [comment]
Guys, I did implement the suggested changes, if you could review it one more time and let me know what you think. 
By the way, thanks:))

**Review by AnnaShliapkina — APPROVED** [review]

**Comment by DmytroLyt** [comment]
> Guys, I did implement the suggested changes, if you could review it one more time and let me know what you think. 
> By the way, thanks:))

Good job! Keep going!

**Review by DmytroLyt — APPROVED** [review]
Good job!
Code is clear, and updated according to notes

**Pull request merged**
